import unittest
from feature_extractors.fext_common import *
from feature_extractors.fext_mem_rw_dump import FextMemRwDump


class TestChunkCreation(unittest.TestCase):
    sample_file = """#
# Memory Access Trace Generated By Pin
#
0x00007ffd37cd1493: W 0x000000361957ec40  1                0x1
0x00007ffd37cd1497: R 0x0000003619691060  8       0x3619690000
0x00007ffd37cd14a0: R 0x0000003619690090  8                  0
0x00007ffd37cd14ac: R 0x000000007ffe0384  1                  0
0x00007ffd37cd14b5: R 0x000000361957ec40  1                0x1
0x00007ffd37cd14bf: R 0x000000361957ec80  8      0x190c9617040
0x00007ffd37cd14c8: R 0x000000361957ec50  8                  0
0x00007ffd38cd14c8: R 0x000000361957ec50  8                  0
0x00007ffd37cd1493: W 0x000000361957ec40  1                0x1
"""

    def test_sample_output_chunks(self):
        test_data = pp_pin_output(self.sample_file.split('\n'))

        df = FextMemRwDump.get_df_from_lines(test_data)
        self.assertEqual(len(df), 9)

        chunk_mem_ref_deltas = FextMemRwDump.get_chunk_mem_deltas(df)
        print chunk_mem_ref_deltas

        self.assertEqual(len(chunk_mem_ref_deltas), 1)
        self.assertEqual(chunk_mem_ref_deltas[0], 230203830252)

    def test_more_than_one_chunk(self, data_sz=20000):
        sample_data = "0x00007ffd37cd1493: W 0x000000361957ec40  1                0x1\n" + \
            "0x00007ffd37cd1493: W 0x000000361957ec41  1                0x1\n"

        sample_data *= data_sz
        test_data = pp_pin_output(sample_data.split('\n'))

        df = FextMemRwDump.get_df_from_lines(test_data)
        self.assertEqual(len(df), data_sz*2)

        chunk_mem_ref_deltas = FextMemRwDump.get_chunk_mem_deltas(df, 10000, FextMemRwDump.MemOffsetMode.DEFAULT)
        self.assertEqual([5000, 5000, 5000, 5000], chunk_mem_ref_deltas)

    def test_read_write_segregation(self):
        sample_data = "0x00007ffd37cd1493: W 0x000000361957ec40  1                0x1\n" + \
                      "0x00007ffd37cd1493: R 0x000000361957ec41  1                0x1\n"

        test_data = pp_pin_output(sample_data.split('\n'))
        df = FextMemRwDump.get_df_from_lines(test_data, 'r')
        self.assertEqual(len(df), 1)

        df = FextMemRwDump.get_df_from_lines(test_data, 'w')
        self.assertEqual(len(df), 1)

        df = FextMemRwDump.get_df_from_lines(test_data, 'rw')
        self.assertEqual(len(df), 2)